### ISSUE TITLE
按你的方法操作，下载不了

### ISSUE THREAD

**Issue by maorenqi** [Zertu/yizhibodownloader#1]
![image](https://user-images.githubusercontent.com/19883006/33363609-1316ecb4-d51c-11e7-95ca-1e6f1b0d5f98.png)
rb报错，视频地址怎么找？还是直接复制一直播的网址？

**Comment by Zertu** [comment]
是这样的，你需要去浏览器里抓包，找到m3u8文件
![image](https://user-images.githubusercontent.com/19660453/33370287-133cf024-d532-11e7-924f-6a6e37bf7bf2.png)
，例如https://alcdn.hls.xiaoka.tv/20171126/e37/c9f/CNVqT_q6NWF6-l1X/index.m3u8，另外我更新了代码，需要你安装ffmpeg并且加入到环境变量，不然不能转码只能看.ts文件

**Comment by maorenqi** [comment]
OK，谢谢！
